### ISSUE TITLE
Package required and available but unsuitable version: ‘randomForestSRC’

### ISSUE THREAD

**Issue by mattdowle** [SoftwareAG/r-pmml#4]
Hi,
Just wondered if `pmml`'s suggest of `randomForestSRC (≤ 2.5.0)` is correct.  That's <= 2.5.0, not >=.
randomForestSRC is on v2.9.3 so `R CMD check` on `pmml` emits :
```
checking package dependencies ... ERROR
./pmml.Rcheck/00check.log:Package required and available but unsuitable version: ‘randomForestSRC’
./pmml.Rcheck/00check.log:See section ‘The DESCRIPTION file’ in the ‘Writing R Extensions’ manual.
./pmml.Rcheck/00check.log:* DONE
./pmml.Rcheck/00check.log:Status: 1 ERROR
```
Therefore `_R_CHECK_FORCE_SUGGESTS_=false` is needed for `pmml`. Is that right?
This came up in revdep testing of data.table release, https://github.com/Rdatatable/data.table/issues/4832. `pmml` suggests `data.table` so it's a revdep I need to test since you might have usage of data.table in tests, examples or vignettes.
Best, Matt

**Comment by dbolotov** [comment]
Hi Matt,

Yes, the suggest is correct. Since version 2.5.1, randomForestSRC has dropped support for the PMML format. This was causing issues in the pmml package, so we stuck with the older release. So far we have kept randomForestSRC in Suggests, but it might be removed from pmml to avoid any problems with versions.

Thanks.
